export { default as Home } from './Home.jsx'
export { default as About } from './About.jsx'
export { default as Test } from './Test.jsx'
export { default as NotFound } from './NotFound.jsx'
export { default as Auth } from './Auth.jsx'
export { default as Dashboard } from './Dashboard.jsx'
export { default as GroupDetails } from './GroupDetails.jsx'